version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your-root-user-password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/src
    ports:
      - "8000:80"
    depends_on:
      - db

