version: 2
jobs:
  build:
    working_directory: ~/pypublisher
    docker:
      - image: circleci/python:3.7
    environment:
      SECRET_KEY: 2i3gn2oq3ig3g2oigmw3
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - '/usr/local/bin'
            - '/usr/local/lib/python3.7/site-packages'
      - run:
          command: |
            pipenv run python manage.py test
